export default function Features() {
  const features = [
    {
      title: "AI Security Analysis",
      description:
        "Detect vulnerabilities, insecure dependencies, and risky coding patterns instantly.",
    },
    {
      title: "Performance Insights",
      description:
        "Analyze bottlenecks, optimization opportunities, and inefficient architecture.",
    },
    {
      title: "Code Quality Score",
      description:
        "Measure maintainability, readability, and overall repository health.",
    },
    {
      title: "GitHub Integration",
      description:
        "Connect repositories directly and fetch live commits, issues, and pull requests.",
    },
    {
      title: "Technical Debt Detection",
      description:
        "Identify outdated patterns, duplicated logic, and scalability concerns.",
    },
    {
      title: "README Intelligence",
      description:
        "AI evaluates documentation quality and provides improvement suggestions.",
    },
    {
      title: "Community Metrics",
      description:
        "Track contributor activity, engagement, issue response time, and project growth.",
    },
    {
      title: "Actionable Recommendations",
      description:
        "Receive prioritized fixes and improvements generated by AI-powered analysis.",
    },
  ];

  return (
    <section className="relative py-32 px-6 overflow-hidden">

      {/* BACKGROUND GLOW */}
      <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[800px] h-[800px] bg-blue-500/5 blur-[140px] rounded-full" />

      <div className="relative z-10 max-w-7xl mx-auto">

        {/* HEADING */}
        <div className="text-center mb-20">

          <p className="text-blue-400 uppercase tracking-[0.3em] text-sm font-semibold mb-4">
            FEATURES
          </p>

          <h2 className="text-5xl md:text-6xl font-black tracking-tight">

            <span className="bg-gradient-to-b from-white to-zinc-500 bg-clip-text text-transparent">
              Everything You Need
            </span>

            <br />

            <span className="text-blue-500">
              To Ship Better Code
            </span>
          </h2>

          <p className="text-zinc-400 text-lg max-w-3xl mx-auto mt-6 leading-relaxed">
            Powerful AI-driven insights designed to improve
            repository quality, maintainability, security,
            and developer productivity.
          </p>
        </div>

        {/* FEATURES GRID */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">

          {features.map((feature, index) => (
            <div
              key={index}
              className="group relative bg-zinc-900/50 border border-zinc-800 rounded-[28px] p-7 backdrop-blur-xl hover:border-zinc-700 transition-all duration-300 hover:-translate-y-1"
            >

              {/* HOVER GLOW */}
              <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition duration-300 bg-blue-500/5 rounded-[28px]" />

              {/* ICON */}
              <div className="w-14 h-14 rounded-2xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center mb-6">

                <div className="w-3 h-3 rounded-full bg-blue-400" />
              </div>

              {/* TITLE */}
              <h3 className="text-xl font-bold text-white mb-4">
                {feature.title}
              </h3>

              {/* DESCRIPTION */}
              <p className="text-zinc-400 leading-7 text-sm">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}